name: digital_scale
version: 1.1.0+0
description: This package was created to communicate with serial and digital scale in flutter
homepage: https://github.com/sergiotucano/digital_scale

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  roundabnt: ^1.0.4+2
  flutter_libserialport: ^0.3.0
  flutter_bluetooth_serial_plus: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
